lib/analysis/network_exposure/libnetwork_exposure.so: \
	BOOST_LIBS := $(BOOST_SYSTEM_LIB)
lib/analysis/network_exposure/libnetwork_exposure.so: \
	BOOST_LIBS := $(BOOST_LIBS:%=-l%)
lib/analysis/network_exposure/libnetwork_exposure.so: \
	DYNAMIC_LIBS := -lpq $(BOOST_LIBS)
lib/analysis/network_exposure/libnetwork_exposure.so: \
	STATIC_LIBS :=
lib/analysis/network_exposure/libnetwork_exposure.so: \
	lib/analysis/network_exposure/network_exposure.o \
	include/ipInformation.o \
	include/timeStamp.o \
	include/stringHelpers.o
