lib/analysis/darkSpaceTargets/libdarkSpaceTargets.so: lib/analysis/darkSpaceTargets/darkSpaceTargets.o \
													  include/postgreSQL.o \
													  include/ipInformation.o \
													  include/timeStamp.o \
													  include/stringHelpers.o
