lib/analysis/networkTraffic/libnetworkTraffic.so: lib/analysis/networkTraffic/networkTraffic.o \
													  include/postgreSQL.o \
													  include/ipInformation.o \
													  include/timeStamp.o \
													  include/stringHelpers.o
