lib/analysis/sqlBruteForcers/libsqlBruteForcers.so: lib/analysis/sqlBruteForcers/sqlBruteForcers.o \
													  include/postgreSQL.o \
													  include/ipInformation.o \
													  include/timeStamp.o \
													  include/stringHelpers.o
