lib/analysis/evasiveTraffic/libevasiveTraffic.so: lib/analysis/evasiveTraffic/evasiveTraffic.o \
													  include/postgreSQL.o \
													  include/ipInformation.o \
													  include/timeStamp.o \
													  include/stringHelpers.o
